### ISSUE TITLE
Clicking on empty slot within a room will sell 0 air, causing NullPointerException

### ISSUE THREAD

**Issue by Seeroh** [MrLetsplay2003/MineBay#1]
Steps to reproduce:

1) Open a MineBay room
2) Click an empty slot
3) Chat will ask for a price
4) Enter Price
5) "Successfully put 0 air for 10 for sale on MineBay"
6) Try and open affected MineBay room
7) NullPointerException!
`[22:14:42] [Server thread/WARN]: java.lang.NullPointerException
[22:14:42] [Server thread/WARN]: 	at me.mrletsplay.minebay.SellItem.getSellItemStack(SellItem.java:52)
[22:14:42] [Server thread/WARN]: 	at me.mrletsplay.minebay.AuctionRoom.getMineBayInv(AuctionRoom.java:201)
[22:14:42] [Server thread/WARN]: 	at me.mrletsplay.minebay.Events.onInvClick(Events.java:119)
[22:14:42] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
[22:14:42] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:14:42] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:14:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[22:14:42] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:14:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[22:14:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:14:42] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:14:42] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[22:14:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[22:14:42] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by MrLetsplay2003** [comment]
Will be fixed in the next update as i said on SpigotMC

**Comment by MrLetsplay2003** [comment]
Fixed
